Revert "Revert "external/mtp: disable MTP_SUPPORT_OBJECTADDDELETE_EVENT because inoity don't support""
This reverts commit 0f7be10b890b4fc9bed78c50154997123304bed1.
fix error: external/mtp-responder/mtp-responder/src/mtp_cmd_handler_util.c:479:(.text._hutil_add_object_entry+0x2105): undefined reference to `g_last_created_dir'

Signed-off-by: yangsong8 <yangsong8@xiaomi.com>