external/mtp: Printing log does not depend on CONFIG_ANDROID_LIBBASE
mtp-responder/src/mtp_init.c:81: undefined reference to `__android_log_buf_print'

Signed-off-by: yangsong8 <yangsong8@xiaomi.com>